### ISSUE TITLE
better README

### ISSUE THREAD

**Issue by shapr** [andrewthad/packed#3]
what does this library do anyway?
Why would I use it?

**Comment by andrewthad** [comment]
Currently, it's something only I use. I'll try to document it soon.

**Comment by chessai** [comment]
@shapr to clarify, this library's API and design are unstable and rely on very new, unchartered features of GHC. This library will most likely not be released until GHC 8.8 or GHC 9.0 lands. That being said, I'll write something up in the README today explaining the motivation behind packed and some parts of the library.

**Comment by shapr** [comment]
fixed!
