### ISSUE TITLE
Needs more unboxed types

### ISSUE THREAD

**Issue by taktoa** [andrewthad/packed#4]
I think there's really too many boxed types in this library.
There's no reason for an identifier _not_ to end in `#`.

**Comment by aljce** [comment]
I find pointer indirections a personal attack.

**Comment by chessai** [comment]
If everything doesn't have a '#' and the end, what is any of this really worth?

**Comment by andrewthad** [comment]
I have a special build of GHC that connects to a Nest  and raises the temperature in my house every time a heap allocation happens.
