### ISSUE TITLE
Slicing operations

### ISSUE THREAD

**Issue by chessai** [andrewthad/packed#5]
Do we want to support them - yes/no, why. A discussion

**Comment by andrewthad** [comment]
I’m inclined to say yes. I think I already have some slicing operations for Bytes (like drop).  I think they are a part of the API for this kind of thing that most people have come to expect. Also, it is important to have unsafe  variants of all of these things that do not perform any bounds checking.

**Comment by chessai** [comment]
Is it possible to write them without having the two Int# everywhere
